tasks:
  - type: "CartesianPlan"
    goal:
      position:
        x: 0.4
        y: 0.1
        z: 0.4
      orientation:
        x: 0.0
        y: 1.0
        z: 0.0
        w: 0.0
    merge: false
    group: "panda_arm"
  - type: "JointPlan"
    goal: [-1.0, -1.0, 0.0, 1.57, 1.3,1.57,0.0]
    merge: true
    group: "panda_arm"
  - type: "CartesianPlan"
    goal:
      position:
        x: 0.2
        y: 0.1
        z: 0.4
      orientation:
        x: 0.0
        y: 1.0
        z: 0.0
        w: 0.0
    merge: true
    group: "panda_arm"
  - type: "JointPlan"
    goal: [0.0, -1.0, -1.0, 1.57, 0.0 ,1.57,0.0]
    merge: true
    group: "panda_arm"
  - type: "CartesianPlan"
    goal:
      position:
        x: 0.4
        y: 0.0
        z: 0.8
      orientation:
        x: 0.0
        y: 1.0
        z: 0.0
        w: 0.0
    merge: true
    group: "panda_arm"